#!/usr/bin/env ruby
# frozen_string_literal: true

require "secretmgr"

cli = Secretmgr::Cli.new
ret = cli.arg_parse(ARGV)
# p 1
if ret
  # p 2
  cli.execute
else
  # p 3
  exit(Secretmgr::Cli::EXIT_CODE_FAILURE)
end
