#!/usr/bin/env ruby
require "secretmgr"

arg = ARGV
cmd = arg[0]
if cmd == "setup"
  arg.shift
  setting_txt_file = arg.shift
  secret_txt_file = arg.shift
else
  setting_yaml_file = arg.shift
  secret_yaml_file = arg.shift
  if (arg[0] == "--template-dir") || (arg[0] == "-d")
    template_dir = arg[1]
    arg.shift
    arg.shift
  end
  if (arg[0] == "--target") || (arg[0] == "-t")
    target = arg[1]
    sub_target = arg[2]
    arg.shift
    arg.shift
    arg.shift
  end
end

case cmd
when "setup"
  sm = Secretmgr::Secretmgr.new(setting_txt_file, secret_txt_file)
  sm.setup
else
  sm = Secretmgr::Secretmgr.new(setting_yaml_file, secret_yaml_file)
  sm.load
  sm.make(template_dir, target, sub_target)
end
